package controleaereo.telas;

/**
 *
 * @author garrien
 */
public class PrincipalJFrame extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalJFrame
     */
    public PrincipalJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelConteudo = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItemAviao = new javax.swing.JMenuItem();
        jMenuItemOrigem = new javax.swing.JMenuItem();
        jMenuItemDestino = new javax.swing.JMenuItem();
        jMenuItemData = new javax.swing.JMenuItem();
        jMenuItemHorario = new javax.swing.JMenuItem();
        jMenuItemCadRota = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanelConteudo.setLayout(new javax.swing.BoxLayout(jPanelConteudo, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanelConteudo);

        jMenu.setText("File");

        jMenuItemAviao.setText("Avião");
        jMenuItemAviao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAviaoActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemAviao);

        jMenuItemOrigem.setText("Origem");
        jMenuItemOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOrigemActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemOrigem);

        jMenuItemDestino.setText("Destino");
        jMenuItemDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDestinoActionPerformed(evt);
            }
        });
        jMenu.add(jMenuItemDestino);

        jMenuItemData.setText("Data");
        jMenu.add(jMenuItemData);

        jMenuItemHorario.setText("Horario");
        jMenu.add(jMenuItemHorario);

        jMenuItemCadRota.setText("Cadastrar rota");
        jMenu.add(jMenuItemCadRota);

        jMenuBar.add(jMenu);
        jMenuBar.add(jMenu2);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAviaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAviaoActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new AviaoJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemAviaoActionPerformed

    private void jMenuItemOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOrigemActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new OrigemJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemOrigemActionPerformed

    private void jMenuItemDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDestinoActionPerformed
        // TODO add your handling code here:
        jPanelConteudo.removeAll();
        jPanelConteudo.add(new DestinoJPanel());
        jPanelConteudo.setVisible(false);
        jPanelConteudo.setVisible(true);
    }//GEN-LAST:event_jMenuItemDestinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemAviao;
    private javax.swing.JMenuItem jMenuItemCadRota;
    private javax.swing.JMenuItem jMenuItemData;
    private javax.swing.JMenuItem jMenuItemDestino;
    private javax.swing.JMenuItem jMenuItemHorario;
    private javax.swing.JMenuItem jMenuItemOrigem;
    private javax.swing.JPanel jPanelConteudo;
    // End of variables declaration//GEN-END:variables
}
